### PR TITLE
[Don't merge] differences with Officialserver branch

### PR DESCRIPTION
**Pull request by StefArma**
Just leave it here so i can compare Officialserver and master easily

### CODE REVIEW

**Comment by zalexki** [comment]
This shouldn't be here.
I suggest you to use a [diff tool](https://www.git-tower.com/blog/diff-tools-windows/) between both repositories on your PC (plus you easily can do diff between versions/releases).
Or if you must fork the project and do this kind of PR in your fork repo :)

**Comment by StefArma** [comment]
well, let's say i mess up with officialserver version, barbolani could see instantly what i've done, just by linking here

**Comment by zalexki** [comment]
haha i see then if it's fixed, we can close it ?

**Comment by StefArma** [comment]
nope, because there is no error yet :P i'll really keep this as a difference viewer ... ;)

**Pull request closed without merging**
